CREATE TABLE PRODUTOS (
	ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NOME VARCHAR(90),
	QUANTIDADE INT,
	VALOR DOUBLE
);
	
INSERT INTO PRODUTOS (NOME, QUANTIDADE, VALOR) VALUES ('MELANCIA', 50, 200);
INSERT INTO PRODUTOS (NOME, QUANTIDADE, VALOR) VALUES ('LARANJA', 150, 82.50);
INSERT INTO PRODUTOS (NOME, QUANTIDADE, VALOR) VALUES ('BATATA', 96, 24.96);
INSERT INTO PRODUTOS (NOME, QUANTIDADE, VALOR) VALUES ('FEIJAO', 75, 517.50);

